[package]
name = "rust_optics"
version = "0.1.0"
authors = ["Gillett Hernandez <gillett.hernandez@gmail.com>"]
edition = "2018"
default-run = "forward_tracing"

[dependencies]
itertools = "0.10.0"
image = "0.23.12"
rayon = "1.3.0"
num_cpus = "1.13.0"
toml = "0.5"
serde = { version = "1.0.106", features = ["derive"] }
rand = "0.8.3"
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
nalgebra = "0.27.0"
minifb = "0.19.3"
math =  { git = "https://github.com/gillett-hernandez/rust_cg_math" }
exr = "0.9.0"
structopt = { version = "0.3", features = [ "paw" ] }
paw = "1.0"
line_drawing = "0.8.0"

[build-dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"

[lib]
name = "optics"
path = "src/lib.rs"

[profile.dev]
opt-level = 3
panic='abort'
debug=true

[profile.test]
opt-level = 0
