[package]
name = "rust_optics"
version = "0.3.0"
authors = ["Gillett Hernandez <gillett.hernandez@gmail.com>"]
edition = "2024"

[features]
dev = ["line_drawing", "image"]
omp = ["dep:nalgebra"]
poly = ["dep:nalgebra"]


[dependencies]
itertools = "~0.15"
math = { git = "https://github.com/gillett-hernandez/rust_cg_math" }
thermite = { git = "https://github.com/raygon-renderer/thermite" }
minifb = "~0.28"
nalgebra = { version = "~0.35", optional = true }
num_cpus = "~1.17"
ordered-float = "~5.3"
paw = "~1.0"
rand = "~0.10"
rayon = "~1.12"
serde = { version = "~1.0", features = ["derive"] }
toml = "~0.8"
image = { version = "~0.25", optional = true }
line_drawing = { version = "~1.0", optional = true }

[dev-dependencies]
crossbeam = "~0.8"
structopt = { version = "~0.3", features = ["paw"] }
linefeed = "~0.6"
egui = "~0.27"
eframe = "~0.27"
egui_extras = "~0.27"
line_drawing = "~1.0"
criterion = "~0.8"
plotters = "~0.3"

[build-dependencies]
serde = { version = "~1.0", features = ["derive"] }

[lib]
name = "optics"
path = "src/lib.rs"

[[example]]
name = "lens_analysis"
required-features = ["dev", "poly"]

[[example]]
name = "radial_efficiency"

[[example]]
name = "poly_error"
required-features = ["poly"]

[[bench]]
name = "optics_benches"
harness = false
