[package]
name = "rust_optics"
version = "0.1.0"
authors = ["Gillett Hernandez <gillett.hernandez@gmail.com>"]
edition = "2018"
default-run = "forward_tracing"

[dependencies]
image = "0.23.12"
itertools = "0.10.0"
line_drawing = "0.8.1"
math =  { git = "https://github.com/gillett-hernandez/rust_cg_math" }
minifb = "0.19.3"
nalgebra = "0.29.0"
num_cpus = "1.13.0"
ordered-float = "2.8.0"
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
paw = "1.0"
rand = "0.8.4"
rayon = "1.5.0"
serde = { version = "1.0.120", features = ["derive"] }
structopt = { version = "0.3", features = [ "paw" ] }
toml = "0.5"

[build-dependencies]
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.52"

[lib]
name = "optics"
path = "src/lib.rs"

[profile.dev]
opt-level = 3
panic='abort'
debug=true

[profile.test]
opt-level = 0
